# Generated by Django 2.1.2 on 2018-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('country', models.IntegerField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grid',
            },
        ),
    ]
